# Generated by Django 2.2.6 on 2019-11-03 00:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('año_nacimiento', models.DateField(blank=True, null=True)),
                ('año_defuncion', models.DateField(blank=True, null=True, verbose_name='defuncion')),
            ],
            options={
                'ordering': ['apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado_libro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Identificación única para este libro en particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Disponible'), ('a', 'Agotado')], default='d', help_text='Estado de libro', max_length=1)),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genero',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now, help_text='Pequeña descripcion del libro', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.AddField(
            model_name='estado_libro',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libros.Autor'),
        ),
    ]
