# Generated by Django 2.2.6 on 2019-11-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20191102_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('año_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['apellido', 'primer_nombre'],
            },
        ),
    ]
